### ISSUE TITLE
Error (addon failed to load) on each startup

### ISSUE THREAD

**Issue by dynnamic** [luoliyan/chinese-support-redux#118] opened 2020-02-15 19:07 UTC
I use Anki 2.1.20 for Mac. 

Everytime I open Anki after installing the addon I get this error message:
<img width="413" alt="Screen Shot 2020-02-15 at 11 57 49 AM" src="https://user-images.githubusercontent.com/25778927/74593737-ae653a80-4feb-11ea-9b54-5c700c15b931.png">

What should I do to fix this?
Thank you.

**Comment by 3ter** [comment] 2020-02-16 20:38
Duplicate of #114 

I copied the _hotfix_ (replace `chinese.py` by [this](https://raw.githubusercontent.com/khonkhortisan/chinese-support-redux/c5595456438111067441e5c17e612ff220c643f3/chinese/templates/chinese.py)) by @khonkhortisan and I can continue using the addon.

**Comment by RobynElizabeth** [comment] 2020-03-02 05:28
I have this same exact problem. 
I’m not a coder I’m just a regular person , so I can’t understand what am I replacing ‘chinese.py’ with ? The link is to whole page of text .  Please help :(

**Comment by RobynElizabeth** [comment] 2020-03-02 05:29
> Duplicate of #114
> 
> I copied the _hotfix_ (replace `chinese.py` by [this](https://raw.githubusercontent.com/khonkhortisan/chinese-support-redux/c5595456438111067441e5c17e612ff220c643f3/chinese/templates/chinese.py)) by @khonkhortisan and I can continue using the addon.


I have this same exact problem.
I’m not a coder I’m just a regular person , so I can’t understand what am I replacing ‘chinese.py’ with ? The link is to whole page of text . Please help :(

**Comment by 3ter** [comment] 2020-03-02 20:44
#### Step by step application of the hotfix
1. Browse to the `templates` folder by entering `%Appdata%\Roaming\Anki2\addons21\1128979221\templates` in Windows Explorer
![image](https://user-images.githubusercontent.com/11499929/75715471-bc92a680-5ccd-11ea-9e03-1d9f3ca066f2.png)
2. Open the file `Chinese.py` with `notepad`
![image](https://user-images.githubusercontent.com/11499929/75715768-40e52980-5cce-11ea-803a-4922917e9247.png)
3. Browse to the ["page of text"](https://raw.githubusercontent.com/khonkhortisan/chinese-support-redux/c5595456438111067441e5c17e612ff220c643f3/chinese/templates/chinese.py), click in the text and type <kbd>ctrl</kbd>+<kbd>A</kbd> to select all of it
![image](https://user-images.githubusercontent.com/11499929/75715818-59edda80-5cce-11ea-8432-3d56617d4929.png)
4. Back to the file opened in `notepad`, select everything there (<kbd>ctrl</kbd>+<kbd>A</kbd>) and replace it with <kbd>ctrl</kbd>+<kbd>V</kbd>
5. Save the file and the Addon should be usable again 🎉 

The alternative is to wait until the PR by @khonkhortisan has been processed or another solution has been found.

**Comment by JamesBream** [comment] 2020-03-06 16:54
@luoliyan Had chance to look at this one?

**Comment by raisintoasty** [comment] 2020-04-09 01:46
Thank you this worked for me, I have v 2.1.22 (Windows 10)

**Comment by lollylan** [comment] 2020-04-13 14:22
This worked for me as well, thanks!

**Comment by LewProudfoot** [comment] 2020-05-24 16:30
Thank you @3ter, worked fine for me.

**Comment by razor3lade25** [comment] 2020-05-25 12:12
Hi whats the solution for Mac users?

**Comment by razor3lade25** [comment] 2020-05-25 12:13
How do I browse to the templates folder for Mac?

**Comment by LewProudfoot** [comment] 2020-05-25 13:04
I haven't used a Mac for twenty years, I can't help there.
Lew Proudfoot
The Wind In My Face

Kingman, AZ
 

    On Monday, May 25, 2020, 05:14:05 AM MST, razor3lade25 <notifications@github.com> wrote:  
 
 


How do I browse to the templates folder for Mac?

**Comment by 3ter** [comment] 2020-05-25 15:20
> How do I browse to the templates folder for Mac?

I suggest to check the [file locations section in the manual](https://docs.ankiweb.net/#/files?id=file-locations).
```
~/Library/Application Support/Anki2
```

**Comment by razor3lade25** [comment] 2020-05-30 09:42
thanks so much yep found it!

**Comment by razor3lade25** [comment] 2020-05-30 09:42
> > How do I browse to the templates folder for Mac?
> 
> @razor3lade25 I suggest to check the [file locations section in the manual](https://docs.ankiweb.net/#/files?id=file-locations).
> 
> ```
> ~/Library/Application Support/Anki2
> ```

Thanks so much yep found it!

**Comment by luoliyan** [comment] 2020-05-31 07:02
Thanks for your patience everyone. I'll upload the changes in a few hours.

**Closed by luoliyan** 2020-05-31 07:02 UTC
Labels: bug, fixed
