### ISSUE TITLE
Error when starting anki after addon installation on mac

### ISSUE THREAD

**Issue by georgLs** [luoliyan/chinese-support-redux#119] opened 2020-03-12 21:08 UTC
When loading 'Chinese Support Redux v0130':
Traceback (most recent call last):
  File "aqt/addons.py", line 205, in loadAddons
  File "/Users/georgsiemund/Library/Application Support/Anki2/addons21/1128979221/__init__.py", line 23, in <module>
    from . import main
  File "/Users/georgsiemund/Library/Application Support/Anki2/addons21/1128979221/main.py", line 34, in <module>
    from .templates import chinese, ruby
  File "/Users/georgsiemund/Library/Application Support/Anki2/addons21/1128979221/templates/chinese.py", line 14, in <module>
    from anki.template.hint import hint
ModuleNotFoundError: No module named 'anki.template.hint'; 'anki.template' is not a package

**Comment by matrixritter** [comment] 2020-03-28 05:55
I've changed line 14 in chinese.py to "from anki.template import hint" and got this error:

Traceback (most recent call last):
  File "aqt/addons.py", line 208, in loadAddons
  File "/Users/klaus/Library/Application Support/Anki2/addons21/1128979221/__init__.py", line 23, in <module>
    from . import main
  File "/Users/klaus/Library/Application Support/Anki2/addons21/1128979221/main.py", line 34, in <module>
    from .templates import chinese, ruby
  File "/Users/klaus/Library/Application Support/Anki2/addons21/1128979221/templates/chinese.py", line 14, in <module>
    from anki.template import hint
ImportError: cannot import name 'hint' from 'anki.template' (/Applications/Anki.app/Contents/MacOS/anki/template.pyc)

I've searched in this and in Anki repository and found nothing related to this "hint" function...that might be my fault. 

I think there's a file missing, written by the author of the plugin.

**Comment by Pilichuli** [comment] 2020-03-28 18:35
![Captura de pantalla 2020-03-28 a las 19 15 10](https://user-images.githubusercontent.com/62810378/77830779-2cf4e200-712b-11ea-8ffd-9f35b5b8a3ed.png)
And now I can't continue to create new cards:(

**Comment by Pilichuli** [comment] 2020-03-29 12:24
I downdated to 2.1 15 standart and now it runs, but the meaning field doesn't fill itself automatically

**Comment by hans** [comment] 2020-03-29 15:25
Duplicate of #118 . See the hotfix solution in that thread: https://github.com/luoliyan/chinese-support-redux/issues/118#issuecomment-593612143

**Comment by luoliyan** [comment] 2020-05-31 07:03
That's correct - this should be resolved along with #118. An update will be pushed to AnkiWeb later today.

**Closed by luoliyan** 2020-05-31 07:03 UTC
