### ISSUE TITLE
Unreliable field filling

### ISSUE THREAD

**Issue by muellert** [luoliyan/chinese-support-redux#54] opened 2019-03-24 19:12 UTC
**Is your feature request related to a problem? Please describe.**

I have a deck with a lot of notes, for which I have a simplified and a traditional field each. The relevant fields are named "Hanzi" and "Traditional". This deck started out with Anki 1.x and the Chinese support available in there, from ttempe, and I am using the "Chinese (Advanced)" model for my notes.

When I was adding or editing a node in the old Anki (ie, it can also be an old note which I created long ago), I start out filling the simplified Chinese into the "Hanzi" field. In Anki 1.x and Anki 2.0.x, I was able to then press the Tab key while the cursor was in the Hanzi field, and if I was online, the software would fill most of the other fields as needed. Eg. it would automatically fill the Traditional field, but also Meaning, Ruby, Sound etc.

Oh. I just see that it is probably the same as #53.

**Describe the solution you'd like**

I would like to see this module to have the same behaviour regarding the auto-filling of fields.

**Describe alternatives you've considered**

None.

**Additional context**

From my POV, it looks like this module autofills no field at all, but I've changed the subject of this ticket to highlight those fields which are most important to me.

**Comment by luoliyan** [comment] 2019-04-02 06:57
If it's the same as #53, the problem is most likely that you haven't clicked `汉字` to enable the add-on for that note type.

**Comment by muellert** [comment] 2019-04-08 16:46
I have enabled the auto-fill, and I see a black bar underneath the "汉字“, but auto-fill remains a hit-and-miss experience. Sometimes, it works, sometimes, it doesn't. It doesn't really work quite frequently, imho,  if I am trying to use it from the browser window. But I haven't added many words recently, just tried to complete old entries, so I can't really compare.

**Comment by muellert** [comment] 2019-04-09 16:53
I notice that the "Color" field (almost?) never gets filled, and that the colouring of the Bopomofo field is wrong at times. Eg. I have this word in my dictionary: 错误跟踪器, which has two words with tone 1, and the other words with tone 4. But the Bopomofo is all marked as if there were only the fourth tone. This happens on 'Add'. I am now running Anki 2.1.11+ (ie, HEAD).

**Comment by luoliyan** [comment] 2019-04-22 13:09
The issue with the `Color` field is probably the same as #57 

I'll keep this issue open for the hit-and-miss filling, though.

**Comment by jugurtha6656** [comment] 2019-04-23 06:40
so awesome you keep support up like this thank you for working on these issues!

**Comment by DanGould** [comment] 2019-05-03 19:28
I am also having a problem with Color field  filling when using bopomofo transcription. for example, if I type the word 「超過」 the Reading is shown ㄔㄠㄐㄧㄚˋ in blue and the color field is shown as 超 in blue. if I add a space after the reading of the first character (i.e. ㄔㄠ ㄐㄧㄚˋ) then the coloring in the reading is corrected and both characters appear in the correct colors in the Color field. I think a space in the generation would fix this problem (for me)

**Comment by luoliyan** [comment] 2019-08-15 06:56
I think there's been enough improvement that I'll close this now.

Feel free to open a new issue with any examples that still aren't working correctly.

**Closed by luoliyan** 2019-08-15 06:56 UTC
Labels: bug, fixed
