### ISSUE TITLE
Ruby Bopomofo Problem

### ISSUE THREAD

**Issue by DrPatriot** [luoliyan/chinese-support-redux#63] opened 2019-04-16 03:05 UTC
The bopomofo reading for a word is appearing over only the first of the word's characters

1. Add fields 'Bopomofo' and 'RubyBPMF' to a Chinese (Advanced) style note type
2. Enter 加拿大人 into Hanzi field
3. Autofill other fields
4. Ruby BPMF appears as if the first hanzi had the reading for the whole word with the other three hanzi absent. (Like 加(ㄐㄧㄚㄋㄚˊㄉㄚˋㄖㄣˊ) )

**Screenshots**
![anki_RxdJUlYyFB](https://user-images.githubusercontent.com/24511173/56178999-3b0d2980-5fd2-11e9-86f9-093192868560.png)
You can see that ruby pinyin is working fine, though. 

 - OS: Windows
 - Anki 2.1.9
- Chinese Support Version v0.10.3

**Comment by luoliyan** [comment] 2019-04-22 12:58
Hi everyone. I've made progress on this, and I intend to have it fixed by the end of the week. I'll close this, since it appears to be a duplicate of of #32

**Comment by luoliyan** [comment] 2019-04-22 13:02
Thanks for reporting. This appears to be related to issue #32, which I'll hopefully have a fix for shortly.

I'll close this for now, but feel free to reopen if the problem persists in the next release.

**Closed** 2019-04-22 13:02 UTC
Labels: bug
