### ISSUE TITLE
Google Audio

### ISSUE THREAD

**Issue by arnoldbro** [luoliyan/chinese-support-redux#165] opened 2020-11-19 18:08 UTC
**Describe the bug**
As others have said the addon seems to have trouble fetching the sound from google. Baidu still works and is sufficient for the time being but the audio quality is much lower than google. I appreciate your work on this thanks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]
 - Anki Version [e.g. v2.0.52, v2.1.5]
- Chinese Support Version [e.g. v0.5.3-beta]

**Additional context**

**Comment by psii** [comment] 2020-11-22 02:34
This is a duplicate of #161, in which [I provided a solution for this issue](https://github.com/luoliyan/chinese-support-redux/issues/161#issuecomment-727697730).

**Comment by luoliyan** [comment] 2021-02-24 07:11
I'll close this in favour of #161, just so we can deal with all the gTTS issues in a single thread.

**Closed by luoliyan** 2021-02-24 07:11 UTC
Labels: bug, difficulty: moderate, duplicate
