### ISSUE TITLE
Plug-in error when loading Anki

### ISSUE THREAD

**Issue by deeriox** [luoliyan/chinese-support-redux#148] opened 2020-08-11 16:04 UTC
**Describe the bug**
Plug in doesn't work. Error shows up when opening Anki. No fields automatically fill up.

**Screenshots**

![image](https://user-images.githubusercontent.com/69523708/89919662-25dbf580-dc2e-11ea-9b66-54561aba1ba0.png)

**Specs (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - Anki Version 2.1.26 (70784154)
- Chinese Support Version [e.g. v0.5.3-beta]

**Additional context**

_**I also use V2 Experimental Scheduler**_

Other add-ons I have:
![image](https://user-images.githubusercontent.com/69523708/89920354-dfd36180-dc2e-11ea-9f67-7b41c8ea60f4.png)

**Comment by huilinshanghai** [comment] 2020-08-28 09:18
Hi, I have the same problem... if you find a solution, I would be very grateful if you could tell me. 
Thanks!

**Comment by luoliyan** [comment] 2021-02-24 06:40
This seems to be related to API changes in Anki - which is to say, the add-on is referencing Anki code that has been relocated or removed.

If the add-on hasn't loaded properly, the missing `汉字` button is expected behaviour.

Fixing this will be near the top of the to-do list.

**Comment by luoliyan** [comment] 2021-03-30 14:06
I can't reproduce this with the latest add-on and Anki versions.

Closing for now, but please feel free to reopen if this error is still occurring.

**Closed by luoliyan** 2021-03-30 14:06 UTC
Labels: bug, can't reproduce, severity: high
