### ISSUE TITLE
Wrong and broken Ruby output with the Hanzi "答案"

### ISSUE THREAD

**Issue by danielrenninghoff** [luoliyan/chinese-support-redux#50] opened 2019-02-06 11:39 UTC
**Describe the bug**
When creating a card with the Hanzi "答案" and using the Pinyin and Ruby generation functionality of this addon, the resulting Ruby output is wrong.

**To Reproduce**
1. Create card with 答案 as Hanzi field
2. Select Fill Notes -> Fill Transcription and Color
3. Resulting Pinyin field is correct: dáàn
4. Resulting Ruby field is incorrect:

HTML code of the ruby field:
```html
<span class="tone4"><ruby>答<rt>dáàn</rt></ruby></span>
```
**Expected behavior**
The correct HTML would be:
```html
<span class="tone2"><ruby>答<rt>dá</rt></ruby></span><span class="tone4"><ruby>案<rt>àn</rt></ruby></span>
```
**Screenshots**
<img width="361" alt="bildschirmfoto 2019-02-06 um 19 38 06" src="https://user-images.githubusercontent.com/1737566/52338922-ab358700-2a46-11e9-882c-30caeab4f540.png">

**Specs (please complete the following information):**
 - OS: macOS
 - Anki Version v2.1.8
- Chinese Support Version v0.10.0

**Comment by luoliyan** [comment] 2019-02-06 14:31
Thanks. Is this fixed for you in v0.10.1?

**Comment by danielrenninghoff** [comment] 2019-02-06 14:54
I've just tried it with the v0.10.1 from github master and the issue still persists.

**Comment by luoliyan** [comment] 2019-02-06 15:17
Okay, well I guess I'll need a bit more time in the that case. Thanks for testing.

**Comment by 3ter** [comment] 2019-02-23 13:42
Hi there,

so I suppose this (see below) is due to the same error, correct? (the punctuation is lost along with the 案):

![image](https://user-images.githubusercontent.com/11499929/53287194-cdcedc00-3778-11e9-9031-4647ff817185.png)

PS I've downloaded the addon from GitHub to be sure it's the latest version: __version__ = '0.10.1-beta'

**Comment by luoliyan** [comment] 2019-04-22 12:59
Hi everyone. I've made progress on this, and I intend to have it fixed by the end of the week. I'll close this, since it appears to be a duplicate of of #32

**Closed by luoliyan** 2019-04-22 12:59 UTC
Labels: bug
