### ISSUE TITLE
Problem with Zhuyin transcription

### ISSUE THREAD

**Issue by onaphta** [luoliyan/chinese-support-redux#47] opened 2019-01-20 12:00 UTC
**Describe the bug**
After the last update, the problem with the space in the zhuyin/pinyin transcription persists (affecting tone colour and the ruby field). I have noticed that there is a new problem with the zhuyin transcription: some tone marks disappear, although the pinyin field is correct.
Examples:
神韻 zhuyin: ㄕㄣㄩㄣˋ but pinying: shényùn (right tones)
巨大無比 zhuyin: ㄐㄩㄉㄚˋ ㄨㄅㄧˇ but pinyin: jùdà wúbǐ
不錯 ㄅㄨㄘㄨㄛˋ but bùcuò
試圖 ㄕㄊㄨˊ but shìtú
不好意思 ㄅㄨㄏㄠㄧㄙˋ but bùhǎoyìsi
百戰百勝　ㄅㄞㄓㄢㄅㄞㄕㄥˋ　but bǎizhànbǎishèng

So it seems to be a problem with zhuyin. I just tried with a few words and expressions, for most of them zhuyin has wrong tones.

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version 2.1.7 (a6c34fd7) Qt 5.12.0 PyQt 5.11.3
- Chinese Support Version 0.10

**Comment by luoliyan** [comment] 2019-01-20 16:32
Thanks. This is good information.

When you say the tone marks disappear, do you mean they are initially correct? Are you doing anything other than entering the characters (such as editing another field)?

The underlying logic of the Zhuyin function is correct now (it is *over* covered by the test suite, if anything). So the problem is occurring at the integration level, and I need to know more detail to debug that.

Are you able to tell me the contents of every field before and after the bad output, as well as which field has focus at before and after? I only need one example for this (巨大無比 would probably be the best).

**Comment by onaphta** [comment] 2019-01-21 06:16
Hi,

No, the tone marks aren't initially correct for zhuyin (but they are fine for pinyin).  The problem is happening with almost all the words and expressions I add: i have to manually correct the zhuyin tones. 

[I created a gif image, it should be quite clear, let me know if you need more examples](https://my.pcloud.com/publink/show?code=XZh11w7ZJllPKD9WlUySNukO543PsjBzvy7y). I use tab after editing a field.

**Comment by luoliyan** [comment] 2019-02-06 14:30
@onaphta, can you let me know if v0.10.1 fixes this?

**Comment by onaphta** [comment] 2019-02-06 15:17
It doesn't seem to fix it, same behaviour.

**Comment by onaphta** [comment] 2019-03-04 13:21
Hi, 
while we wait for the fix, is there a way of installing a previous version of the Zhuyin function? Thanks!

**Comment by luoliyan** [comment] 2019-08-14 15:12
It should be fixed now.

**Closed by luoliyan** 2019-08-14 15:12 UTC
Labels: bug, fixed
